# Generated by Django 3.1 on 2020-09-06 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key='True', serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='teacher_timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('First_lech', models.CharField(max_length=50)),
                ('sec_lech', models.CharField(max_length=50)),
                ('third_lech', models.CharField(max_length=50)),
                ('fourth_lech', models.CharField(max_length=50)),
                ('fifth_lech', models.CharField(max_length=50)),
                ('sixth_lech', models.CharField(max_length=50)),
                ('sev_lech', models.CharField(max_length=50)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
    ]
