# Generated by Django 3.1 on 2020-09-06 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher_timetable_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_lech_link', models.CharField(max_length=50)),
                ('sec_lech_link', models.CharField(max_length=50)),
                ('third_lech_link', models.CharField(max_length=50)),
                ('fourth_lech_link', models.CharField(max_length=50)),
                ('fifth_lech_link', models.CharField(max_length=50)),
                ('sixth_lech_link', models.CharField(max_length=50)),
                ('sev_lech_link', models.CharField(max_length=50)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.teacher_timetable')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='teacher_subj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_class', models.CharField(max_length=50)),
                ('sec_class', models.CharField(max_length=50)),
                ('third_class', models.CharField(max_length=50)),
                ('fourth_class', models.CharField(max_length=50)),
                ('fifth_class', models.CharField(max_length=50)),
                ('sixth_class', models.CharField(max_length=50)),
                ('sev_class', models.CharField(max_length=50)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.teacher_timetable')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
    ]
