# Generated by Django 3.1 on 2020-09-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200906_1740'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserForm',
        ),
    ]
