# Generated by Django 3.1 on 2020-09-06 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_delete_userform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
