# Generated by Django 3.1 on 2020-09-06 12:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0005_delete_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='teacher_class',
            new_name='teacher_subj',
        ),
    ]
