# Generated by Django 3.1 on 2020-09-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_student_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student_info',
        ),
        migrations.RemoveField(
            model_name='teacher_timetable_link',
            name='day',
        ),
        migrations.RemoveField(
            model_name='teacher_timetable_link',
            name='name',
        ),
        migrations.AddField(
            model_name='teacher_timetable',
            name='First_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher_timetable',
            name='fifth_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher_timetable',
            name='fourth_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher_timetable',
            name='sec_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher_timetable',
            name='sev_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher_timetable',
            name='sixth_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher_timetable',
            name='third_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_timetable',
            name='First_lech',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_timetable',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Monday', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher_timetable',
            name='fifth_lech',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_timetable',
            name='fourth_lech',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_timetable',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher_timetable',
            name='sec_lech',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_timetable',
            name='sev_lech',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_timetable',
            name='sixth_lech',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_timetable',
            name='third_lech',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='teacher_subj',
        ),
        migrations.DeleteModel(
            name='teacher_timetable_link',
        ),
    ]
