# Generated by Django 3.1 on 2020-09-11 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200911_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_timetable',
            name='user',
        ),
    ]
