# Generated by Django 3.1 on 2020-09-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_teacher_timetable_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_timetable',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
